// <autogenerated />
using Microsoft.AspNetCore.Components;
using Microsoft.FluentUI.AspNetCore.Components;
using Microsoft.JSInterop;
using OllamaFluentUIChat.Models.DTO;
using OllamaFluentUIChat.Services;
using OllamaFluentUIChat.Services.Interfaces.Repositories;
using OllamaFluentUIChat.Services.Interfaces.Services;
using System.Text.Json;

namespace OllamaFluentUIChat.Components.Pages
{
    public partial class ChatBase
    {
        [Inject] protected IAiChatService AiChatService { get; set; } = default!;
        [Inject] private ConversationsClientService ConversationsClient { get; set; } = null!;
        [Inject] private IAppSettingsRepository AppSettingsRepo{ get; set; } = null!;

        [Inject] protected IJSRuntime JS { get; set; } = default!;

        protected List<ChatMessageDto> Messages { get; set; } = new();
        protected string currentInput = string.Empty;
        protected bool IsStreaming { get; set; } = false;

        protected ElementReference messagesContainerRef;
        protected FluentTextArea? chatInputRefFluent;

        private DotNetObjectReference<ChatBase>? dotNetRef;
        private CancellationTokenSource? _cts;

        protected int limiteTokens { get; set; }
        protected int tokensEstimados { get; set; }
        protected int tokensUsados { get; set; } = 0;
        protected bool ShowTokenWarning => limiteTokens > 0 && ((double)tokensEstimados / limiteTokens) >= 0.80;

        protected bool isProcessing = false;
        protected string modeloAtual = "";
        protected string? selectedConversationId;
        protected List<ConversationItem> conversations = new();
        protected bool showConfirmNewConversation = false;
        protected bool showConfirmDeleteConversation = false;
        protected List<ChatMessage> messages = new();

        protected CancellationTokenSource? chatCts;
        protected ChatMessage? currentAssistantMessage;
        protected ElementReference chatInputRef;

        protected override async Task OnInitializedAsync()
        {
            await LoadConversations();
            modeloAtual = (await AppSettingsRepo.GetSettingsAsync()).AiModelName;
        }

        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
            {
                dotNetRef = DotNetObjectReference.Create(this);

                // Pequeno delay para garantir o ciclo completo de Shadow DOM do Fluent UI
                await Task.Delay(50);

                if (chatInputRefFluent != null)
                {
                    // Passamos o .Element, que aponta para a tag <fluent-text-area> real
                    await JS.InvokeVoidAsync("chatInput.attachHandlers", chatInputRefFluent.Element, dotNetRef);
                }
            }
        }

        protected async Task SendMessageAsync()
        {
            if (string.IsNullOrWhiteSpace(currentInput) || IsStreaming) return;

            var userMessage = new ChatMessageDto { Role = "user", Content = currentInput.Trim() };
            Messages.Add(userMessage);
            currentInput = string.Empty;

            // Reset imediato à altura da textarea no JS para evitar saltos visuais
            if (chatInputRefFluent != null)
            {
                await JS.InvokeVoidAsync("chatInput.resetHeight", chatInputRefFluent.Element);
            }

            var aiMessage = new ChatMessageDto
            {
                Role = "assistant",
                Content = string.Empty
            };
            Messages.Add(aiMessage);

            IsStreaming = true;
            StateHasChanged();

            _cts = new CancellationTokenSource();

            try
            {
                // Clona o histórico para envio, excluindo o placeholder da IA que acabámos de criar
                var messagesToSend = new List<ChatMessageDto>(Messages.SkipLast(1));

                // Configuração opcional de idioma direto na lista, se aplicável ao teu projeto
                // messagesToSend.Insert(0, new ChatMessageDto { Role = "system", Content = "Respond in Portuguese." });

                var stream = AiChatService.StreamChatAsync(
                    messagesToSend,
                    null, // connectionId (obsoleto sem o SignalR/API)
                    Guid.NewGuid().ToString(), // correlationId (obsoleto sem o SignalR/API)
                    _cts.Token
                );

                await foreach (var chunk in stream)
                {
                    aiMessage.Content += chunk;

                    // Executa a função otimizada de scroll no contentor de mensagens
                    await JS.InvokeVoidAsync("chatScroll.scrollDuringStream", messagesContainerRef);
                    StateHasChanged();
                }
            }
            catch (OperationCanceledException)
            {
                // Fluxo interrompido normalmente pelo utilizador ou navegação
            }
            catch (Exception ex)
            {
                aiMessage.Content = $"Ocorreu um erro ao comunicar com o modelo: {ex.Message}";
            }
            finally
            {
                IsStreaming = false;
                _cts?.Dispose();
                _cts = null;
                StateHasChanged();
            }
        }

        [JSInvokable]
        public async Task OnEnterPressedFromJs()
        {
            // Callback disparado quando o JS deteta um Enter (sem Shift)
            await InvokeAsync(SendMessageAsync);
        }

        protected string GetTokenClass()
        {
            if (limiteTokens <= 0) return "";

            double ratio = (double)tokensEstimados / limiteTokens;

            if (ratio < 0.40)
                return "token-low";      // verde
            else if (ratio < 0.75)
                return "token-medium";   // amarelo
            else
                return "token-high";     // vermelho
        }

        protected string GetTokenPercent()
        {
            if (limiteTokens <= 0) return "0%";
            double ratio = (double)tokensEstimados / limiteTokens;
            ratio = Math.Clamp(ratio, 0, 1);
            return (ratio * 100).ToString("0.##") + "%";
        }


        protected string GetWarningClass()
        {
            if (limiteTokens <= 0) return "";

            double ratio = (double)tokensEstimados / limiteTokens;

            if (ratio >= 0.90)
                return "token-warning-high";   // vermelho forte
            else
                return "token-warning-medium"; // amarelo
        }


        protected async Task ClearChatAsync()
        {
            if (IsStreaming)
            {
                _cts?.Cancel();
            }

            Messages.Clear();
            currentInput = string.Empty;

            if (chatInputRefFluent != null)
            {
                await JS.InvokeVoidAsync("chatInput.resetHeight", chatInputRefFluent.Element);
            }

            StateHasChanged();
        }

        // Conversations
        async Task ShowConfirmNewConversation()
        {
            if (messages.Count > 0)
            {
                showConfirmNewConversation = true;
                await InvokeAsync(StateHasChanged);
            }
            else
            {
                await NewConversation();
            }
        }
        void ShowConfirmDeleteConversation() => showConfirmDeleteConversation = true;

        async Task OnConfirmYes()
        {
            showConfirmNewConversation = false;
            await NewConversation();
        }

        void OnConfirmNo() => showConfirmNewConversation = false;
        void OnConfirmDeleteNo() => showConfirmDeleteConversation = false;

        async Task NewConversation()
        {
            try { chatCts?.Cancel(); } catch { }
            chatCts?.Dispose(); chatCts = null;

            messages.Clear(); 
            currentAssistantMessage = null;

            await InvokeAsync(StateHasChanged);

            try
            {
                await JS.InvokeVoidAsync("focusElement", chatInputRef);
                var id = Guid.NewGuid().ToString();
                var title = "Conversation " + DateTime.Now.ToString("g");
                var conv = new Conversation { Id = id, Title = title, Json = "[]" };
                await ConversationsClient.UpsertAsync(conv);
                await LoadConversations();
                selectedConversationId = id;
                await InvokeAsync(StateHasChanged);
                try
                {
                    //if (toastObj != null)
                    //{
                    //    ToastTitle = "Conversation";
                    //    ToastContent = "Started new conversation";
                    //    ToastCssClass = "e-toast-success";
                    //    await InvokeAsync(StateHasChanged);
                    //    await toastObj.ShowAsync();
                    //}
                }
                catch { }
            }
            catch { }
        }

       protected async Task LoadConversations()
        {
            try
            {
                var arr = await ConversationsClient.GetAllAsync();
                if (arr != null)
                {
                    conversations.Clear();
                    conversations = arr
                        .Select(c => new ConversationItem { Id = c.Id, Title = c.Title, Json = c.Json })
                        .ToList();

                    selectedConversationId = null;
                    await InvokeAsync(StateHasChanged);
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error loading conversations: " + ex.Message);
            }
        }

        async Task OnConversationSelected(string? id)
        {
            selectedConversationId = id;
            if (string.IsNullOrEmpty(id)) return;
            var conv = conversations.FirstOrDefault(c => c.Id == id);
            if (conv != null)
            {
                messages.Clear();
                if (!string.IsNullOrEmpty(conv.Json))
                {
                    try
                    {
                        var restored = JsonSerializer.Deserialize<List<ChatMessage>>(conv.Json);
                        if (restored != null) messages.AddRange(restored);
                    }
                    catch { }
                }
                await InvokeAsync(StateHasChanged);
            }
        }


        public async ValueTask DisposeAsync()
        {
            if (_cts != null)
            {
                _cts.Cancel();
                _cts.Dispose();
            }

            if (chatInputRefFluent != null)
            {
                try
                {
                    await JS.InvokeVoidAsync("chatInput.detachHandlers", chatInputRefFluent.Element);
                }
                catch (JSDisconnectedException)
                {
                    // Ignora se o circuito SignalR do Blazor já tiver fechado
                }
            }

            dotNetRef?.Dispose();
        }
    }
}
