using System.Text;

namespace OllamaFluentUIChat.PromptTemplates
{
    public static class EvaluatePromptTemplate
    {
        public static async Task<string> EvaluationCopyPrompt(string originalPrompt, string modelResponse)
        {
            StringBuilder sb = new();
            sb.Append("Act as a strict Artificial Intelligence judge. ");
            sb.Append("Analyze the quality of the response generated by a small local model for the given prompt. ");
            sb.AppendLine($"\nOriginal Prompt Submitted:\n{originalPrompt} ");
            sb.AppendLine($"Response Generated by Local Model: \n{modelResponse} ");
            sb.AppendLine("\n");

            sb.Append("Response Instructions:\n");
            sb.Append("Evaluate the response using a scale from 1 to 5 for two distinct criteria, plus a final score:\n");
            sb.Append("- Factual Score: Accuracy, logic, and factual correctness (1-5).\n");
            sb.Append("- Formatting Score: Markdown correctness, clean table syntax, and layout (1-5).\n");
            sb.Append("- Final Score: Your overall evaluation taking both into account (1-5).\n\n");
            sb.Append("Note: Minor formatting bugs should only penalize the Formatting Score. Do not heavily lower the Factual Score unless the information itself is wrong or missing due to truncation.\n\n");

            sb.Append("You MUST provide your evaluation strictly in the following format (do not include any other text outside these blocks):\n");
            sb.AppendLine("FACTUAL_SCORE: [1-5]");
            sb.AppendLine("FORMATTING_SCORE: [1-5]");
            sb.AppendLine("FINAL_SCORE: [1-5]");
            sb.AppendLine("DESCRIPTION: [Brief description of the evaluation, max 3 sentences]");

            return sb.ToString();
        }
    }
}