using System.Text;

namespace OllamaFluentUIChat.PromptTemplates
{
    public static class EvaluatePromptTemplate
    {
        public static async Task<string> EvaluationCopyPrompt(string originalPrompt, string modelResponse, string trainingYear)
        {
            StringBuilder sb = new();
            sb.Append("Act as a strict Artificial Intelligence judge. ");
            sb.Append("Analyze the quality of the response generated by a small local model for the given prompt. ");

            sb.AppendLine($"\n[CRITICAL CONTEXT] The local model being evaluated was trained in {trainingYear}. Do not penalize it for lacking knowledge of events, data, or software updates that occurred after this year.");

            sb.AppendLine($"\nOriginal Prompt Submitted:\n{originalPrompt} ");
            sb.AppendLine($"Response Generated by Local Model: \n{modelResponse} ");
            sb.AppendLine("\n");

            sb.Append("Response Instructions:\n");
            sb.Append("Evaluate the response using a scale from 1 to 5 for two distinct criteria, plus a final score:\n");
            sb.Append("- Factual Score: Accuracy, logical reasoning, and depth of the factual information actually provided. Do not penalize this score for a lack of real-world details that occurred post-training year. If text is truncated, rate the factual correctness of only the text that is present.\n");
            sb.Append("- Formatting Score: Markdown correctness, layout, adherence to word counts, completeness, and whether the text was cut off/truncated.\n");
            sb.Append("- Final Score: Your overall evaluation taking both into account (1-5).\n\n");

            sb.Append($"Note: If a response terminates abruptly or fails a length constraint, heavily penalize the Formatting Score, NOT the Factual Score. The Factual Score must strictly judge whether the generated claims are true, logical, and accurate up to the year {trainingYear}.");

            sb.Append("You MUST provide your evaluation strictly in the following format (do not include any other text outside these blocks):\n");
            sb.AppendLine("FACTUAL_SCORE: [1-5]");
            sb.AppendLine("FORMATTING_SCORE: [1-5]");
            sb.AppendLine("FINAL_SCORE: [1-5]");
            sb.AppendLine("DESCRIPTION: [Brief description of the evaluation, max 4 sentences]");

            return sb.ToString();
        }
    }
}