using System.Text;

namespace OllamaFluentUIChat.PromptTemplates;

public static class EvaluatePromptTemplate
{
    public static async Task<string> EvaluationCopyPrompt(string originalPrompt, string modelResponse)
    {
        StringBuilder sb = new();
        sb.Append("Act as a strict Artificial Intelligence judge. ");
        sb.Append("Analyze the factual, logical, and grammatical quality of the response generated by a small local model for the given prompt. ");
        sb.AppendLine($"Original Prompt Submitted: {originalPrompt} ");
        sb.AppendLine($"Response Generated by Local Model: {modelResponse} ");
        sb.AppendLine();
        sb.Append("Response Instructions: Give strictly a score from 1 to 5 (where 1 is terrible/total hallucination and 5 is perfect/factual), ");
        sb.Append("followed by a brief description, with a maximum of three sentences.");
        sb.AppendLine("\n");
        sb.Append("Please provide your evaluation in the following format:");
        sb.AppendLine("\n");
        sb.Append("Score: [1-5]");
        sb.AppendLine("\n");
        sb.Append("Description: [Brief description of the evaluation, max 3 sentences]");
        sb.AppendLine();
        sb.Append("Please ensure that your evaluation is concise, objective, and based solely on the content of the response provided by the local model.");
        var formattedText = sb.ToString();
        return formattedText;
    }

}
